package com.next360.common.enums;

public enum AuditAction {
    SELLER_APPROVED,
    SELLER_REJECTED,
    SELLER_SUSPENDED,
    SELLER_BLOCKED,
    CERTIFICATE_APPROVED,
    CERTIFICATE_REJECTED,
    CERTIFICATE_REVOKED,
    PRODUCT_APPROVED,
    PRODUCT_REJECTED,
    PRODUCT_HIDDEN,
    CLASSIFICATION_CHANGED,
    ORDER_CANCELLED_BY_ADMIN,
    REFUND_APPROVED,
    PAYOUT_ADJUSTED
}
